spring.application.name=userServices

# Configuración de Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=test123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=DonTacosFoodSecretKeyJWT2026SeguridadBackend
jwt.expiration=3600000

